### ISSUE TITLE
processing fails at functional site prediction step

### ISSUE THREAD

**Issue by biodavidjm** [jdrudolph/photon#14] opened 2017-11-15 22:16 UTC
Hi, I have a couple of things to ask

1. I run the tool using proteins with only one ph site unequivocally detected in the protein, then photon crashes at the 4th step when the subnetwork has to be extracted. Is there any way to let it finish without having multiple sites per protein, i.e., add a checkpoint to either:
- skip that step of predicting functional sites even if there is only one in the protein or 
- Still predict functional sites, even if there is only one in the protein.

2. Speaking of which, in order to see the 'progress report' I have to use the `dev` version of the container. When are you planning to make it the latest version?

Thanks and congratulation for the tool!

**Comment by jdrudolph** [comment] 2017-11-16 17:32
The `dev` branch was integrated into the `master` brand already some time ago https://github.com/jdrudolph/photon/pull/7. Did you try the latest version?

**Comment by biodavidjm** [comment] 2017-11-16 18:45
You are right: I have to add the label `jdrudolph/photon:lastest` to get the one incorporating those changes (just `jdrudolph/photon` was not pulling the latest one for some reason). 

what about my second question?

THANKS a lot

**Comment by jdrudolph** [comment] 2017-11-21 11:10
the problem is not related to whether or not only one site per protein is reported.

I reduced the example data to only one site per protein and it was running just fine.
I was able to reproduce an error with the functional site prediction when the data contained only about 200 sites, which I fixed in 6ff3bae.

Please try the latest version and reopen the issue if the problem persists

**Closed as completed by jdrudolph** 2017-11-21 11:10 UTC
