### ISSUE TITLE
Issue during PHOTON reading parameter

### ISSUE THREAD

**Issue by Sarkawt-Hamad** [jdrudolph/photon#25] opened 2019-12-20 15:45 UTC
Dear Jan Rudolph

Hello,

I have up to dated all packages even perseus and anaconda python, but during the PHOTON this error always come out. Could you have a look it and what is wrong? Please.

Best regards,

Sarkawt
![Issue1](https://user-images.githubusercontent.com/58376654/71266164-1f6bd700-2348-11ea-88d0-c3a3d412310c.jpg)

**Comment by jdrudolph** [comment] 2019-12-23 14:07
On the bottom of the error you can see that it fails to convert '0,964' into a floating point number. The expected format would be '0.964'. This could either be due to computer settings, or because of bad formatting in an input file that you use.
Please make sure to change you windows to English number format. If you are using any external `.csv` files make sure to change the number format there as well. All numbers should be in English format with a dot and not a comma separating the digits.

**Comment by Sarkawt-Hamad** [comment] 2019-12-23 21:54
Dear Jan Rudolph,

Thank you for your reply. I have changed comouter setting to English.  
Now PHOTON works and network with matrix table are appeared, but still  
when I want to visualize the PHOTON network still nothing coming out.

Would you suggest to overcome this problem? I do apologize for boring  
you. I am realy interested in your technique and I want to use  PHOTON.

Best regards,

Sarkawt
Quoting Jan Rudolph <notifications@github.com>:

> On the bottom of the error you can see that it fails to convert  
> '0,964' into a floating point number. The expected format would be  
> '0.964'. This could either be due to computer settings, or because  
> of bad formatting in an input file that you use.
> Please make sure to change you windows to English number format. If  
> you are using any external `.csv` files make sure to change the  
> number format there as well. All numbers should be in English format  
> with a dot and not a comma separating the digits.

**Comment by jdrudolph** [comment] 2020-08-02 21:31
Please investigate the tabular representation of the result to understand what might be going wrong. In general consider the following resources:
 * Perseus mailing list: https://groups.google.com/forum/#!forum/perseus-list
 * MaxQuant youtube channel: https://www.youtube.com/channel/UCKYzYTm1cnmc0CFAMhxDO8w

Since this issue is not reproducible for me and seems to be not due to bugs in the `photon_ptm` code I will close this issue. Feel free to reopen if neccessary.
Best, Jan

**Closed as completed by jdrudolph** 2020-08-02 21:31 UTC
